export const russianViolet = '#241848'
export const rainbowIndigo = '#2A346E'
export const pearlyPurple = '#A367AA'
export const milk = '#FCFBF4'
export const jasmine = '#FDE27F'
export const atomicTangerine = '#FB9A6F'

export const brightGray = '#EEEEEE'
export const chineseSilver = '#CCCCCC'
export const spanishGray = '#999999'
export const graniteGray = '#666666'
export const darkCharcoal = '#333333'
export const black = '#000000'
